# Generated by Django 3.2.5 on 2021-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
